name = "wow-companion-auth"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Set these as secrets via: wrangler secret put BNET_CLIENT_ID
# and: wrangler secret put BNET_CLIENT_SECRET

[[kv_namespaces]]
binding = "CACHE"
id = "9a579130311a464dbff60b223c19fd64"
preview_id = "728bbec084df47c0b539d074a0cdd2d6"
